run:
  timeout: 2m
linters:
  enable:
    - gofmt
    - govet
    - goimports
    - ineffassign
    - misspell
    - unconvert
    - unused
linters-settings:
  goimports:
    local-prefixes: github.com/nholuongut/argocd-image-updater
issues:
  exclude-files:
    - ".*\\.pb\\.go"
  exclude-dirs:
    - vendor/
